# Generated by Django 3.1.4 on 2021-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
